name: Node CI

on:
  workflow_dispatch:
  push:
    branches:
      - actions-ubuntu
      - master
      - develop
      - release/**
  pull_request:
    branches:
      - '**'
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      test-only:
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  prepare-npm-cache-ubuntu:
    uses: ./.github/workflows/prepare-cache.yml
    with:
      os: ubuntu-24.04
  prepare-npm-cache-macos:
    uses: ./.github/workflows/prepare-cache.yml
    with:
      os: macos-latest
  prepare-npm-cache-windows:
    uses: ./.github/workflows/prepare-cache.yml
    with:
      os: windows-latest

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    needs: prepare-npm-cache-ubuntu

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - name: Install
        run: npm ci
      - name: Run ESLint
        run: npm run lint

  # TEST
  test-linux:
    uses: ./.github/workflows/test.yml
    needs: prepare-npm-cache-ubuntu
    with:
      os: ubuntu-24.04
  test-macos:
    uses: ./.github/workflows/test.yml
    needs: prepare-npm-cache-macos
    with:
      os: macos-latest
  test-windows:
    uses: ./.github/workflows/test.yml
    needs: prepare-npm-cache-windows
    with:
      os: windows-latest

  # BUNDLE
  bundle-linux:
    uses: ./.github/workflows/webpack.yml
    needs: test-linux
    with:
      os: ubuntu-24.04
  bundle-mac:
    uses: ./.github/workflows/webpack.yml
    needs: test-macos
    with:
      os: macos-latest
  bundle-windows:
    uses: ./.github/workflows/webpack.yml
    needs: test-windows
    with:
      os: windows-latest

  # BUILD
  build-linux:
    uses: ./.github/workflows/build.yml
    needs: bundle-linux
    with:
      os: ubuntu-24.04
      # test-only: true   (it says "test-only" is not defined in workflow)
  build-mac:
    uses: ./.github/workflows/build.yml
    needs: bundle-mac
    with:
      os: macos-latest
      test-only: true
  build-windows:
    uses: ./.github/workflows/build.yml
    needs: bundle-windows
    with:
      os: windows-latest
      test-only: true
